# the name of your track or event
name = "Browsers & Platforms"

# the name handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Dietrich Ayala"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

# the event venue name (will show up on the event card - TODO)
venueName = "Hypatia"

# the event times (shows up in the event card)
times = "10:00 - 13:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
# priority = 1

# a description of the track.
# will show up when the user clicks the event card.
description = """
Learn the current status, ongoing challenges, and upcoming work to integrate IPFS and related technologies into browsers and the web itself, operating systems and other libraries, toolkits, environments and more.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   16:00 (On 30 Oct, 1h Camp wrapup begins at 16:00)
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon




[[timeslots]]
startTime="10:00"
speakers=["@Dietrich Ayala (@autonome)"]
title="Intro"
description="Welcome, overview"


[[timeslots]]
startTime="10:10"
speakers=["@Mauve Signweaver (@rangermauve)"]
title="IPFS in Web Protocol Handlers with Agregore Browser"
description="We'll be showcasing how IPFS can have deep integration with web protocol handlers, and will be answering the question \"What does it mean to POST to `ipfs://`?\""


[[timeslots]]
startTime="10:30"
speakers=["@Anirudha Bose (@onyb)"]
title="Making Brave an InterPlanetary browser"
description="Brave is building a privacy-first internet stack with a private browser, search, web3 wallet, and more. In this session, we'll look at the state of IPFS and Filecoin integrations in Brave, and learn about some of the lesser known features in Brave that makes it an interplanetary browser."


[[timeslots]]
startTime="10:50"
speakers=["@Javier Fernandez (@javifernandez)"]
title="Chrome pre-defined Custom Handlers for IPFS"
description="High-level overview of the refactoring Implemented in Chrome's source code to define a dedicated component for the Custom Handlers logic. Thanks to this refactoring, we have improved the support for Chrome embedders to implement their own pre-defined Custom Handlers for the schemes they consider strategic. Patching Chrome to add a pre-defined Custom Handler to manage IPFS schemes is now trivial, reducing considerably the efforts of embedders to deal with rebases in order to sync with Chrome upstream."


[[timeslots]]
startTime="11:10"
speakers=["@BREAK"]
title="BREAK"
description="BREAK"


[[timeslots]]
startTime="11:20"
speakers=["@Ilya Kreymer (@ikreymer)"]
title="Intro to Decentralized Web Archiving using Webrecorder and IPFS"
description="The Webrecorder project open source tools to 'record' web pages as they load, creating high-fidelity interactive web archives which can then be stored on IPFS in a standard format. These interactive archives can then be loaded directly in the browser, much like video or PDFs, using custom viewer tools. This session will provide a brief intro to high fidelity web archiving workflows and tools."


[[timeslots]]
startTime="11:30"
speakers=["@David Justice (@meandavejustice)"]
title="Introducing pin-tweet-to-ipfs: Webrecorder + web3.storage"
description="Brief introduction to pin-tweet-to-ipfs. The first IPFS-Enabled extension. Marrying one of Webrecorder's browser-based archiving tools (express.archiveweb.page) and web3.storage to display the power of IPFS to non technical users."


[[timeslots]]
startTime="11:40"
speakers=["@Ilya Kreymer (@ikreymer)"]
title="Make your own web archives with Webrecorder tools (Hands-On Demo)"
description="Want to archive a web page and put it on IPFS? Or, run a larger crawl automatically and upload several web archives (as WACZ) files to IPFS? In this lightning talk, we'll demo several additional tools, including our ArchiveWeb.page extension, Browsertrix Crawler crawling system, and our new IPFS WACZ Uploader for easily uploading web archives to IPFS in bulk. Attendees who bring their laptop will be able to follow along or try the tools on their own later"


[[timeslots]]
startTime="11:50"
speakers=["@Fabrice Desré (@fabricedesre)"]
title="IPFS Goes Mobile"
description="Capyloon is an experimental web based mobile OS. It aims at giving users more control over their digital life, with decentralized technologies as a cornerstone of the solution. We'll talk about the early steps, current status and what to expect next."


[[timeslots]]
startTime="12:10"
speakers=["@Lidel (@lidel)"]
title="Gateways of the Future (and Now Too)"
description="HTTP gateways are a key onramp for IPFS usage not only by browsers, but tools, APIs and more. Learn about the state of the IPFS HTTP gateway implementation in Kubo today, and new features and changes coming soon."


[[timeslots]]
startTime="12:20"
speakers=["@Mark Gaiser (@markg85)"]
title="Challenges in IPFS Integrations with Open Source Projects"
description="Going over some of the challenges we faced with implementing IPFS in open source projects. The lessons we've learned and what is still planned ahead."


[[timeslots]]
startTime="12:30"
speakers=["@David Justice (@meandavejustice)"]
title="Announcing Durin"
description="Announcing Durin (ipfs on mobile) and exploring our next steps"


[[timeslots]]
startTime="12:40"
speakers=["@Gabriel Herrero-Beaumont"]
title="IPFS, Tauri and Mintter Hypertext Documents"
description="How we have integrated IPFS, Tauri and Mintter Hypertext Documents to enable open collaboration. We will explain our requirements for an Open and local-first Hypertext System and how IPFS and Tauri have help us to build the system."


[[timeslots]]
startTime="13:00"
speakers=["@Jorropo"]
title="Feather - A File-oriented IPFS Light Client"
description="Explain how we store files on IPFS and how this can be used to make IPFS light clients."




