# the name of your track or event
name = "Measurement and Performance"


# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Yiannis Psaras"

# the start date of the event
date = "2022-10-28"

# how many days the event lasts (1 - N)
days = 1

venueName = "Madriu"


# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "Intermediate"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
priority = 1

# a description of the track.
# will show up when the user clicks the event card.
description = """
  A data-driven approach to the design and operation of IPFS 
  and libp2p through rigorous network measurements, performance evaluation and 
  recommendations for builders and operators.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 13:00 (Day 1 is 10-12 keynotes, 12-13 lunch)
# - recommended end:   17:00, you can run to 18:00 if needed
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="13:00"
speakers=["Yiannis Psaras"]
title="Data-Driven Protocol Design: What it is and what are the benefits"
description=""

[[timeslots]]
startTime="13:30"
speakers=["Leo Balduf"]
title="Bitswap and IPFS real-time metrics analysis"
description=""

[[timeslots]]
startTime="14:00"
speakers=["Guillaume Michel"]
title="DHT Routing Table Health"
description=""

[[timeslots]]
startTime="14:30"
speakers=["Mikel Cortes"]
title="A Deep Dive into Provider Records"
description=""

[[timeslots]]
startTime="15:00"
speakers=[]
title="Coffee Break"
description=""

[[timeslots]]
startTime="15:30"
speakers=["Dennis Trautwein"]
title="The IPFS Network From The Hydra's PoV"
description=""

[[timeslots]]
startTime="16:00"
speakers=["Pedro Akos Costa"]
title="Lessons from IPFS workloads and implications for Multi-Level DHTs"
description=""

[[timeslots]]
startTime="16:20"
speakers=["Thibault Meunier"]
title="Monitoring Cloudflare's IPFS Gateways"
description=""

[[timeslots]]
startTime="16:40"
speakers=["Michal Krol"]
title="Identifying CID Eclipse Attacks through network measurements"
description=""

[[timeslots]]
startTime="17:00"
speakers=[]
title="Open Discussion: Bring your own ideas!"
description=""

[[timeslots]]
startTime="17:30"
speakers=[]
title="End"
description=""
