# the name of your track or event
name = "Measurement and Performance Unconf"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Yiannis Psaras"

# the start date of the event
date = "2022-10-29"

# how many days the event lasts (1 - N)
days = 1

venueName = "Hypatia"


# the event times (shows up in the event card)
times = "14:00 - 17:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Unconf"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """A data-driven approach to the design and operation of IPFS and libp2p through rigorous network measurements, performance evaluation and recommendations for builders and operators.

In this part of the track we will have breakout sessions on a number of different topics of interest to the wider community. We will look into our roadmap for 2023 and do live design work on the measurement experiments we plan to set up and run.

If you have items that will help your project and which you want us to try and fit into our roadmap, this is the session to bring them up!"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="14:00"
speakers=["Yiannis Psaras"]
title="ProbeLab 2023 Roadmap"
description=""

[[timeslots]]
startTime="14:25"
speakers=["Ian Davis"]
title="Talk: Testing IPFS through Thunderdome"
description=""

[[timeslots]]
startTime="14:45"
speakers=["Luca Nizzardo"]
title="Breakout 1.1: Metrics DAO"
description=""

[[timeslots]]
startTime="14:45"
speakers=["Guillaume Michel"]
title="Breakout 1.2: Bitswap Discovery Success Rate"
description=""

[[timeslots]]
startTime="15:30"
speakers=["Dennis Trautwein"]
title="Breakout 2.1: All the Measurement Tools"
description=""

[[timeslots]]
startTime="15:30"
speakers=["Kelsie Nabben"]
title="Breakout 2.2: Data Governance Patterns for Resilient Infrastructure"
description=""

[[timeslots]]
startTime="15:30"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="15:45"
speakers=["Joao Leitao"]
title="Breakout 3.1: Understanding IPFS through Telemetry"
description=""

[[timeslots]]
startTime="15:45"
speakers=["Guillaume Michel"]
title="Breakout 3.2: The DHT Routing Table Visualisation"
description=""

[[timeslots]]
startTime="16:30"
speakers=["All"]
title="Report Backs and Open Slot for Discussion"
description=""

[[timeslots]]
startTime="17:30"
speakers=[]
title="End"
description=""
